export const initialResults = [
  {
    id: 1,
    profilePicture: "https://randomuser.me/api/portraits/men/79.jpg",
    fullName: "John Doe",
    currentPosition: "Senior Lawyer",
    yearsOfExperience: 10,
    location: "New York, NY",
    lawArea: "Family Law",
    rating: 4.5,
    description: "Experienced in family law with over 10 years of practice.",
    areas: ["Family Law"],
    barAffiliation: "New York Bar Association",
    barAssociation: "NY State Bar",
    province: "New York",
    city: "New York",
    education: "Harvard Law School",
    llb: "Harvard University",
    llm: "Yale University",
    lld: "Not applicable",
    lowerCourts: "5 years",
    highCourt: "5 years",
    certifications: ["Certified Family Law Specialist"],
    caseExperience: "Handled over 200 cases successfully.",
    notableCases: "Doe v. Roe",
    successStories: "Won custody cases for over 100 families.",
    officeAddress: "123 Main St, New York, NY",
    officeHours: "Mon-Fri 9am-5pm",
    consultationModes: ["In-person", "Online"],
    consultationFees: "$200/hour",
    contactNumber: "+1 (555) 123-4567",
    socialMedia: {
      facebook: "https://facebook.com/johndoe",
      whatsapp: "https://wa.me/15551234567",
      linkedin: "https://linkedin.com/in/johndoe",
    },
    reviews: [
      {
        title: "Consultation",
        rating: 5,
        reviewText: "Great consultation, very helpful!",
      },
      {
        title: "Case Handling",
        rating: 4,
        reviewText: "Handled my case professionally.",
      },
    ],
  },
  {
    id: 2,
    profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
    fullName: "Jane Smith",
    currentPosition: "Associate Lawyer",
    yearsOfExperience: 5,
    location: "Los Angeles, CA",
    lawArea: "Criminal Law",
    rating: 4.2,
    description:
      "Specializes in criminal law and has successfully defended many cases.",
    areas: ["Criminal Law"],
    barAffiliation: "California Bar Association",
    barAssociation: "CA State Bar",
    province: "California",
    city: "Los Angeles",
    education: "Stanford Law School",
    llb: "Stanford University",
    llm: "Not applicable",
    lld: "Not applicable",
    lowerCourts: "3 years",
    highCourt: "2 years",
    certifications: ["Certified Criminal Law Specialist"],
    caseExperience: "Defended over 100 criminal cases.",
    notableCases: "Smith v. State",
    successStories: "Won 90% of defended cases.",
    officeAddress: "456 Elm St, Los Angeles, CA",
    officeHours: "Mon-Fri 10am-6pm",
    consultationModes: ["In-person", "Online"],
    consultationFees: "$250/hour",
    contactNumber: "+1 (555) 987-6543",
    socialMedia: {
      facebook: "https://facebook.com/janesmith",
      whatsapp: "https://wa.me/15559876543",
      linkedin: "https://linkedin.com/in/janesmith",
    },
    reviews: [
      {
        title: "Consultation",
        rating: 5,
        reviewText: "Very informative and helpful!",
      },
      {
        title: "Case Handling",
        rating: 4,
        reviewText: "Managed my case with great expertise.",
      },
    ],
  },
];
